language: ruby
rvm:
  - 2.2.3
services:
  - mysql
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database my_test_test;'
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake test
  - bundle exec rubocop $TRAVIS_BUILD_DIR
